"""add is_active to products

Revision ID: ad5e51ff5a11
Revises: 1b4faec0413e
Create Date: 2026-05-22 18:03:12.939391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad5e51ff5a11'
down_revision: Union[str, None] = '1b4faec0413e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add with server_default so existing rows are backfilled, then drop the default
    op.add_column('products', sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.alter_column('products', 'is_active', server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_active')
    # ### end Alembic commands ###
